package org.keycloak.storage.jpa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.PersistenceUnitTransactionType;
import liquibase.Liquibase;
import liquibase.database.jvm.JdbcConnection;
import liquibase.exception.LiquibaseException;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.codefilarete.jumper.schema.DefaultSchemaElementCollector;
import org.codefilarete.jumper.schema.DefaultSchemaElementCollector.Schema;
import org.codefilarete.jumper.schema.PostgreSQLSchemaElementCollector;
import org.codefilarete.jumper.schema.difference.PostgreSQLSchemaDiffer;
import org.codefilarete.tool.collection.CaseInsensitiveSet;
import org.hibernate.cfg.Environment;
import org.hibernate.jpa.boot.spi.Bootstrap;
import org.hibernate.jpa.boot.spi.PersistenceUnitDescriptor;
import org.hibernate.jpa.boot.spi.PersistenceXmlParser;
import org.hibernate.tool.schema.Action;
import org.junit.BeforeClass;
import org.junit.Test;
import org.keycloak.connections.jpa.util.JpaUtils;
import org.postgresql.ds.PGSimpleDataSource;
import org.testcontainers.containers.JdbcDatabaseContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

/**
 * This class is made to compare the schema generated by Liquibase and the one expected by Hibernate.
 * The schemas are deployed on a PostGreSQL TestContainer.
 * The comparison is made with the <a href="http://www.github.com/codefilarete/Jumper">Jumper</a> project.
 *
 * @author Guillaume Mary
 */
public class JPAMigrationTest {
	
	private static final String LIQUIBASE_SCHEMA_NAME = "liquibase";
	private static final String HIBERNATE_SCHEMA_NAME = "hibernate";
	private static final String LIQUIBASE_CHANGELOG_PATH = "META-INF/jpa-changelog-master.xml";
	private static JdbcDatabaseContainer POSTGRESQL_CONTAINER;
	
	@BeforeClass
	public static void startContainers() {
		// Fix for TestContainers 1.21.3 which is not compatible with local Docker environment
		// The best fix would be to upgrade TestContainers to the 1.21.4 but we're stuck on the old one due to the Keycloak dependency onto quarkus-bom
		// which manages it. Though we fix it with this short line of code.
		// see https://github.com/testcontainers/testcontainers-java/issues/11212
		System.setProperty("api.version", "1.44");
		System.out.println("Starting containers");
		POSTGRESQL_CONTAINER = buildContainer();
		POSTGRESQL_CONTAINER.start();
	}
	
	private static JdbcDatabaseContainer buildContainer() {
		JdbcDatabaseContainer result = new PostgreSQLContainer<>(DockerImageName.parse("postgres:14.11"))
				.withReuse(true);
		result
				.withConnectTimeoutSeconds(20)
				.setPortBindings(Arrays.asList(5432 + ":" + 5432));
		return result;
	}
	
	@Test
	public void compareSchemas() throws LiquibaseException, SQLException {
		Connection liquibaseConnection = dataSource(LIQUIBASE_SCHEMA_NAME).getConnection();
		
		Liquibase liquibase = new Liquibase(
				LIQUIBASE_CHANGELOG_PATH,
				new ClassLoaderResourceAccessor(),
				new JdbcConnection(liquibaseConnection));
		liquibase.update();
		
		DefaultSchemaElementCollector liquibaseSchemaElementCollector = new PostgreSQLSchemaElementCollector(liquibaseConnection.getMetaData());
		liquibaseSchemaElementCollector
				.withSchema(LIQUIBASE_SCHEMA_NAME)
				.withTableNamePattern("%");
		
		PGSimpleDataSource hibernateDataSource = dataSource(HIBERNATE_SCHEMA_NAME);
		deployHibernateSchema(hibernateDataSource);
		Connection hibernateConnection = hibernateDataSource.getConnection();
		
		DefaultSchemaElementCollector hibernateSchemaElementCollector = new PostgreSQLSchemaElementCollector(hibernateConnection.getMetaData());
		hibernateSchemaElementCollector
				.withSchema(HIBERNATE_SCHEMA_NAME)
				.withTableNamePattern("%");
		
		PostgreSQLSchemaDiffer schemaDiffer = new PostgreSQLSchemaDiffer();
		Schema liquibaseSchema = liquibaseSchemaElementCollector.collect();
		// we remove particular tables
		Set<String> unmanagedTables = new CaseInsensitiveSet(
				// liquibase changelog management
				"databasechangelog", "databasechangeloglock",
				// this table appeared recently in Keycloak without JPA entity, but still used in code with native access
				"jgroups_ping");
		liquibaseSchema.getTables().removeIf(table -> unmanagedTables.contains(table.getName()));
		Schema hibernateSchema = hibernateSchemaElementCollector.collect();
		schemaDiffer.compareAndPrint(liquibaseSchema, hibernateSchema);
	}
	
	private static PGSimpleDataSource dataSource(String schemaName) {
		JdbcDatabaseContainer jdbcDatabaseContainer = POSTGRESQL_CONTAINER;
		PGSimpleDataSource pgDataSource = new PGSimpleDataSource();
		pgDataSource.setUrl(jdbcDatabaseContainer.getJdbcUrl());
		pgDataSource.setCurrentSchema(schemaName);
		pgDataSource.setUser(jdbcDatabaseContainer.getUsername());
		pgDataSource.setPassword(jdbcDatabaseContainer.getPassword());
		
		try (Connection connection = pgDataSource.getConnection()) {
			PreparedStatement preparedStatement = connection.prepareStatement("create schema if not exists " + schemaName);
			preparedStatement.execute();
			preparedStatement.close();
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
		return pgDataSource;
	}
	
	public void deployHibernateSchema(PGSimpleDataSource hibernateDataSource) {
		Map<String, Object> settings = new HashMap<>();
		settings.put("hibernate.dialect", "org.hibernate.dialect.PostgreSQLDialect");
		settings.put("hibernate.connection.url", hibernateDataSource.getUrl());
		settings.put("hibernate.connection.username", hibernateDataSource.getUser());
		settings.put("hibernate.connection.password", hibernateDataSource.getPassword());
		settings.put("hibernate.current_session_context_class", "thread");
		settings.put("hibernate.show_sql", "true");
		settings.put(Environment.HBM2DDL_AUTO, Action.CREATE_ONLY);
		
		createEntityManagerFactory(settings);
	}
	
	public static EntityManagerFactory createEntityManagerFactory(Map<String, Object> integration) {
		PersistenceXmlParser parser = PersistenceXmlParser.create();
		Collection<PersistenceUnitDescriptor> persistenceUnitDescriptors = parser.parse(Collections.singletonList(JpaUtils.class.getClassLoader().getResource("default-persistence.xml")), PersistenceUnitTransactionType.RESOURCE_LOCAL).values();
		PersistenceUnitDescriptor persistenceUnitDescriptor = persistenceUnitDescriptors.stream()
				.findFirst()
				.orElseThrow(() -> new NoSuchElementException("Cannot find the file 'default-persistence.xml'"));
		
		return Bootstrap.getEntityManagerFactoryBuilder(persistenceUnitDescriptor, integration).build();
	}
}
