package org.keycloak.storage.stalactite;

import java.util.Objects;

import org.codefilarete.stalactite.dsl.entity.EntityMappingConfigurationProvider.EntityMappingConfigurationProviderHolder;
import org.codefilarete.stalactite.dsl.entity.FluentEntityMappingBuilder;
import org.codefilarete.stalactite.dsl.idpolicy.IdentifierPolicy;
import org.codefilarete.stalactite.dsl.naming.ForeignKeyNamingStrategy;
import org.codefilarete.stalactite.engine.PersistenceContext;
import org.codefilarete.stalactite.sql.ddl.Length;
import org.codefilarete.stalactite.sql.ddl.Size;
import org.keycloak.models.jpa.entities.CredentialEntity;
import org.keycloak.models.jpa.entities.FederatedIdentityEntity;
import org.keycloak.models.jpa.entities.FederatedIdentityEntity.Key;
import org.keycloak.models.jpa.entities.UserAttributeEntity;
import org.keycloak.models.jpa.entities.UserEntity;
import org.keycloak.models.jpa.entities.UserRequiredActionEntity;

import static org.codefilarete.stalactite.dsl.MappingEase.compositeKeyBuilder;
import static org.codefilarete.stalactite.dsl.MappingEase.embeddableBuilder;
import static org.codefilarete.stalactite.dsl.MappingEase.entityBuilder;

public class UserEntityPersistenceConfiguration {
	
	private static final Length UUID_LENGTH = Size.length(36);
	
	public static FluentEntityMappingBuilder<UserEntity, String> buildEntityMapping() {
		EntityMappingConfigurationProviderHolder<UserEntity, String> result = new EntityMappingConfigurationProviderHolder<>();
		result.setProvider(entityBuilder(UserEntity.class, String.class)
				.onTable("USER_ENTITY")
                .withForeignKeyNaming(ForeignKeyNamingStrategy.HIBERNATE_7)
                .mapKey(UserEntity::getId, IdentifierPolicy.alreadyAssigned(o -> {}, Objects::isNull))
				.columnName("ID")
				.columnSize(UUID_LENGTH)
				.map(UserEntity::getUsername)
				.map(UserEntity::getFirstName).columnName("FIRST_NAME")
				.map(UserEntity::getCreatedTimestamp).columnName("CREATED_TIMESTAMP")
				.map(UserEntity::getLastName).columnName("LAST_NAME")
				.map(UserEntity::getEmail)
				.map(UserEntity::isEnabled)
				.map(UserEntity::isEmailVerified).columnName("EMAIL_VERIFIED")
				.map(UserEntity::getEmailConstraint).columnName("EMAIL_CONSTRAINT")
				.map(UserEntity::getRealmId).columnName("REALM_ID")
				.map(UserEntity::getFederationLink).columnName("FEDERATION_LINK")
				.map(UserEntity::getServiceAccountClientLink).columnName("SERVICE_ACCOUNT_CLIENT_LINK")
				.map(UserEntity::getNotBefore).columnName("NOT_BEFORE")
				
				.mapOneToMany(UserEntity::getAttributes, entityBuilder(UserAttributeEntity.class, String.class)
						.onTable("USER_ATTRIBUTE")
                        .withForeignKeyNaming(ForeignKeyNamingStrategy.HIBERNATE_7)
						.mapKey(UserAttributeEntity::getId, IdentifierPolicy.alreadyAssigned(o -> {}, Objects::isNull)).columnSize(UUID_LENGTH)
						.map(UserAttributeEntity::getName).mandatory()
						.map(UserAttributeEntity::getValue)
						.map("longValue").columnName("LONG_VALUE")
						.map("longValueHash").columnName("LONG_VALUE_HASH")
						.map("longValueHashLowerCase").columnName("LONG_VALUE_HASH_LOWER_CASE")
						.mapManyToOne(UserAttributeEntity::getUser, result).columnName("USER_ID").mandatory()
				).mappedBy(UserAttributeEntity::getUser)
				.reverseJoinColumn("USER_ID")
				
				// In Keycloak, the requiredActions are mapped as a one-to-many relation with a composite key made of user + action. However,
				// only the user is set as a many-to-one reverse relation which is not logical because it means that only this attribute is used to
				// manage the relation whereas we have a composite key.
				// From my point of view, this relation is much more a Collection with a unique key on both fields user + action. Which matches the
				// domain logic: having a unique same action per user.
				// This way of mapping seems better by looking at the schema generated by Liquibase: it doesn't contain a constraint on those fields,
				// hence meaning that there's a discrepancy between the persistence Annotations and what's in Liquibase.
				.mapCollection(UserEntity::getRequiredActions, UserRequiredActionEntity.class, embeddableBuilder(UserRequiredActionEntity.class)
						.map(UserRequiredActionEntity::getAction).columnName("REQUIRED_ACTION").mandatory())
				.onTable("USER_REQUIRED_ACTION")
				.reverseJoinColumn("USER_ID")
				
				.mapOneToMany(UserEntity::getCredentials, entityBuilder(CredentialEntity.class, String.class)
						.onTable("CREDENTIAL")
                        .withForeignKeyNaming(ForeignKeyNamingStrategy.HIBERNATE_7)
						.mapKey(CredentialEntity::getId, IdentifierPolicy.alreadyAssigned(o -> {}, Objects::isNull)).columnSize(UUID_LENGTH)
						.map(CredentialEntity::getType)
						.map("salt")
						.map(CredentialEntity::getUserLabel).columnName("USER_LABEL")
						.map(CredentialEntity::getCreatedDate).columnName("CREATED_DATE")
						.map(CredentialEntity::getSecretData).columnName("SECRET_DATA")
						.map(CredentialEntity::getCredentialData).columnName("CREDENTIAL_DATA")
						.map(CredentialEntity::getPriority).nullable()
						.versionedBy("version")
				).mappedBy(CredentialEntity::getUser)
				.reverseJoinColumn("USER_ID")
				.mapOneToMany(UserEntity::getFederatedIdentities, entityBuilder(FederatedIdentityEntity.class, FederatedIdentityEntity.Key.class)
						.onTable("FEDERATED_IDENTITY")
						.mapCompositeKey(FederatedIdentityEntity::getKey, compositeKeyBuilder(FederatedIdentityEntity.Key.class)
								.map(Key::getUserId).columnName("USER_ID").columnSize(UUID_LENGTH)
								.map(Key::getIdentityProvider).columnName("IDENTITY_PROVIDER"), o -> {}, Objects::isNull)
						.map(FederatedIdentityEntity::getUserName).columnName("FEDERATED_USERNAME")
						.map(FederatedIdentityEntity::getRealmId).columnName("REALM_ID").columnSize(UUID_LENGTH)
						.map(FederatedIdentityEntity::getToken)
						.map(FederatedIdentityEntity::getUserId).columnName("FEDERATED_USER_ID"))
				.reverseJoinColumn("USER_ID"));
		return result.getProvider();
	}
	
	/**
	 * Initializes the persistence mapping and registers it with the persistence context
	 *
	 * @param persistenceContext the Stalactite persistence context
	 */
	public static void initializePersistence(PersistenceContext persistenceContext) {
		FluentEntityMappingBuilder<UserEntity, String> mapping = buildEntityMapping();
		mapping.build(persistenceContext);
	}
}
